spring:
  profiles:
    active:
    -dev
---
spring:
  profiles: dev #
  application:
    name: microservicecloud-config-dev
---
spring:
  profiles: test #Ի
  application:
    name: microservicecloud-config-test
#뱣ΪUTF-8ʽ